require 'spec_helper'

describe "Fe.get_hash and .get_hashes" do
  include FirstPostWCommentsAndAuthors
  it "returns a hash with the right columns for different ways of invoking, fixture name, :first, :last" do
    ['r1', # By the fixture hash name (auto-generated by Fe)
     :first, # By the first fixture in the .yml file
     :last   # By the last fixture in the yml file
    ].each do |invoke_type| 
      h = Fe.get_hash(:first_post_w_comments_and_authors, Post, invoke_type)
      expect(h).to be_a_kind_of(Hash)
      expect(h.keys - Post.column_names).to be_empty
    end
  end
  it "allows you to get the whole yaml file with get_hash(...,:all)" do
    another_extractor = Fe.extract('Post.all', :name => :all_posts)
    all_way_1 = Fe.get_hash(:all_posts, Post, :all)
    expect(all_way_1).to be_a_kind_of(Hash)
    expect(all_way_1.keys).to eql(['r1','r2']), "This hash is essentially the entire .yml file gobbled up as a data-structure"
  end
  it "provides .get_hashes which returns an array (as syntactic sugar for get_hash...:all" do
    another_extractor = Fe.extract('Post.all', :name => :all_posts)
    all_way_1 = Fe.get_hash(:all_posts, Post, :all)
    all_way_2 = Fe.get_hashes(:all_posts, Post)
    expect(all_way_2).to eql(all_way_1.values)
  end
end
